//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcionUI
    {
        public string IdOpcionUI { get; set; }
        public string IdAplicacion { get; set; }
        public string IdOpcionPadre { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Clase { get; set; }
        public string Url { get; set; }
        public bool Estado { get; set; }
        public int Nivel { get; set; }
        public Nullable<int> NroOrden { get; set; }
    }
}
