//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErickOrlando.Seguridad.Datos
{
    using System;
    
    public partial class UsuarioComplex
    {
        public string IdUsuario { get; set; }
        public string EmpresaLabora { get; set; }
        public string EmpresaDePertenencia { get; set; }
        public string CodSociedadPropietaria { get; set; }
        public string Cargo { get; set; }
        public string DescripcionCargo { get; set; }
        public string CodigoUsuario { get; set; }
        public string Nombres { get; set; }
        public string Dominio { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Correo { get; set; }
        public string DNI { get; set; }
        public bool Estado { get; set; }
        public string Tipo { get; set; }
        public System.DateTime UltimoIngreso { get; set; }
        public string Alias { get; set; }
    }
}
