//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErickOrlando.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string IdUsuario { get; set; }
        public string IdEmpresa { get; set; }
        public string IdEmpresaPertenencia { get; set; }
        public string CodigoUsuario { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string DNI { get; set; }
        public bool Estado { get; set; }
        public string Tipo { get; set; }
        public string Correo { get; set; }
        public string Dominio { get; set; }
        public System.DateTime UltimoIngreso { get; set; }
        public string IdCargoSociedad { get; set; }
        public string Alias { get; set; }
        public string AliasAlterno { get; set; }
    }
}
