//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicaciones
    {
        public string IdAplicacion { get; set; }
        public string NombreAplicacion { get; set; }
        public string Acronimo { get; set; }
        public string Uri { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
        public byte[] UltimoCambio { get; set; }
    }
}
