//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    
    public partial class CargoSociedadComplex
    {
        public string IdCargo { get; set; }
        public string CodigoCargo { get; set; }
        public string Descripcion { get; set; }
        public string CodSociedadPropietaria { get; set; }
    }
}
