//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claves
    {
        public string IdClave { get; set; }
        public string IdUsuario { get; set; }
        public string Password { get; set; }
        public string Pregunta { get; set; }
        public string Respuesta { get; set; }
        public bool Ultimo { get; set; }
        public System.DateTime FechaCambio { get; set; }
    }
}
