//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public string IdEmpresa { get; set; }
        public string CodigoEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string NombreCorto { get; set; }
        public string RUC { get; set; }
    }
}
