//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    
    public partial class PerfilMasivo
    {
        public string IdUsuario { get; set; }
        public string NombresCompletos { get; set; }
        public string Dominio { get; set; }
    }
}
