//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    
    public partial class PerfilUsuarioComplex
    {
        public string IdPerfilUsuario { get; set; }
        public string IdUsuario { get; set; }
        public string IdAplicacion { get; set; }
        public string CodigoUsuario { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombresCompletos { get; set; }
        public string NombreAplicacion { get; set; }
        public string Ruta { get; set; }
        public Nullable<System.DateTime> UltimoIngreso { get; set; }
        public bool Logueado { get; set; }
        public bool Caduca { get; set; }
        public Nullable<System.DateTime> VigenciaInicio { get; set; }
        public Nullable<System.DateTime> VigenciaFin { get; set; }
        public string Dominio { get; set; }
        public string Correo { get; set; }
        public string CodigoCargo { get; set; }
        public string Cargo { get; set; }
        public string Alias { get; set; }
        public string AliasAlterno { get; set; }
    }
}
