//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilUsuario
    {
        public string IdPerfilUsuario { get; set; }
        public string IdUsuario { get; set; }
        public string IdAplicacion { get; set; }
        public System.DateTime UltimoIngreso { get; set; }
        public bool Logueado { get; set; }
        public bool Caduca { get; set; }
        public System.DateTime VigenciaInicio { get; set; }
        public System.DateTime VigenciaFin { get; set; }
        public string Usuario { get; set; }
        public string Placa { get; set; }
    }
}
