//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public string IdPermiso { get; set; }
        public string IdOpcionUI { get; set; }
        public string IdRol { get; set; }
        public string IdAplicacion { get; set; }
        public string IdUsuario { get; set; }
        public bool Conceder { get; set; }
        public string IdRolPerfil { get; set; }
        public string Placa { get; set; }
        public string Usuario { get; set; }
    }
}
