//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.RecursoDetalles = new HashSet<RecursoDetalle>();
            this.RecursoAplicaciones = new HashSet<RecursoAplicacion>();
        }
    
        public string IdRecurso { get; set; }
        public string Descripcion { get; set; }
        public string RutaRecurso { get; set; }
        public string IdRecursoPadre { get; set; }
        public int Nivel { get; set; }
    
        public virtual ICollection<RecursoDetalle> RecursoDetalles { get; set; }
        public virtual ICollection<RecursoAplicacion> RecursoAplicaciones { get; set; }
    }
}
