//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursoPerfil
    {
        public string IdRecursoPerfil { get; set; }
        public string IdPerfilUsuario { get; set; }
        public string IdRecursoDetalle { get; set; }
        public bool Conceder { get; set; }
    }
}
