//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SeguridadEntities : DbContext
    {
        public SeguridadEntities()
            : base("name=SeguridadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claves> Claves { get; set; }
        public virtual DbSet<RolesPerfiles> RolesPerfiles { get; set; }
        public virtual DbSet<Aplicaciones> Aplicaciones { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<OpcionUI> OpcionUI { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Plantilla> Plantilla { get; set; }
        public virtual DbSet<Recurso> Recurso { get; set; }
        public virtual DbSet<RecursoDetalle> RecursoDetalle { get; set; }
        public virtual DbSet<RecursoAplicacion> RecursoAplicacion { get; set; }
        public virtual DbSet<RecursoPerfil> RecursoPerfil { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<CargoSociedad> CargoSociedad { get; set; }
    
        public virtual ObjectResult<Empresas> SelectAllEmpresas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectAllEmpresas");
        }
    
        public virtual ObjectResult<Empresas> SelectAllEmpresas(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectAllEmpresas", mergeOption);
        }
    
        public virtual ObjectResult<UsuarioComplex> SelectAllUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioComplex>("SelectAllUsuarios");
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacion(string idAplicacion)
        {
            var idAplicacionParameter = idAplicacion != null ?
                new ObjectParameter("IdAplicacion", idAplicacion) :
                new ObjectParameter("IdAplicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacion", idAplicacionParameter);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacion(string idAplicacion, MergeOption mergeOption)
        {
            var idAplicacionParameter = idAplicacion != null ?
                new ObjectParameter("IdAplicacion", idAplicacion) :
                new ObjectParameter("IdAplicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacion", mergeOption, idAplicacionParameter);
        }
    
        public virtual ObjectResult<Usuarios> SelectUsuario(string idUsuario)
        {
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuarios>("SelectUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<Usuarios> SelectUsuario(string idUsuario, MergeOption mergeOption)
        {
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuarios>("SelectUsuario", mergeOption, idUsuarioParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresa(string idEmpresa)
        {
            var idEmpresaParameter = idEmpresa != null ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresa", idEmpresaParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresa(string idEmpresa, MergeOption mergeOption)
        {
            var idEmpresaParameter = idEmpresa != null ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresa", mergeOption, idEmpresaParameter);
        }
    
        public virtual ObjectResult<Roles> SelectRol(string idAplicacionicacion)
        {
            var idAplicacionicacionParameter = idAplicacionicacion != null ?
                new ObjectParameter("IdAplicacionicacion", idAplicacionicacion) :
                new ObjectParameter("IdAplicacionicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Roles>("SelectRol", idAplicacionicacionParameter);
        }
    
        public virtual ObjectResult<Roles> SelectRol(string idAplicacionicacion, MergeOption mergeOption)
        {
            var idAplicacionicacionParameter = idAplicacionicacion != null ?
                new ObjectParameter("IdAplicacionicacion", idAplicacionicacion) :
                new ObjectParameter("IdAplicacionicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Roles>("SelectRol", mergeOption, idAplicacionicacionParameter);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAllAplicacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAllAplicacion");
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAllAplicacion(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAllAplicacion", mergeOption);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacionByName(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacionByName", nombreParameter);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacionByName(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacionByName", mergeOption, nombreParameter);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacionByTag(string acronimo)
        {
            var acronimoParameter = acronimo != null ?
                new ObjectParameter("Acronimo", acronimo) :
                new ObjectParameter("Acronimo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacionByTag", acronimoParameter);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacionByTag(string acronimo, MergeOption mergeOption)
        {
            var acronimoParameter = acronimo != null ?
                new ObjectParameter("Acronimo", acronimo) :
                new ObjectParameter("Acronimo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacionByTag", mergeOption, acronimoParameter);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacionByUri(string ruta)
        {
            var rutaParameter = ruta != null ?
                new ObjectParameter("Ruta", ruta) :
                new ObjectParameter("Ruta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacionByUri", rutaParameter);
        }
    
        public virtual ObjectResult<Aplicaciones> SelectAplicacionByUri(string ruta, MergeOption mergeOption)
        {
            var rutaParameter = ruta != null ?
                new ObjectParameter("Ruta", ruta) :
                new ObjectParameter("Ruta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Aplicaciones>("SelectAplicacionByUri", mergeOption, rutaParameter);
        }
    
        public virtual ObjectResult<UsuarioComplex> SelectUsuarioByCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioComplex>("SelectUsuarioByCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<UsuarioComplex> SelectUsuarioByName(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioComplex>("SelectUsuarioByName", nombreParameter);
        }
    
        public virtual ObjectResult<UsuarioComplex> SelectUsuarioByApePat(string apellidoPaterno)
        {
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioComplex>("SelectUsuarioByApePat", apellidoPaternoParameter);
        }
    
        public virtual ObjectResult<UsuarioComplex> SelectUsuarioByApeMat(string apellidoMaterno)
        {
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioComplex>("SelectUsuarioByApeMat", apellidoMaternoParameter);
        }
    
        public virtual ObjectResult<UsuarioComplex> SelectUsuarioByDNI(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioComplex>("SelectUsuarioByDNI", dNIParameter);
        }
    
        public virtual ObjectResult<UsuarioComplex> SelectUsuarioByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioComplex>("SelectUsuarioByEmail", emailParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByCodigo(string codigo, MergeOption mergeOption)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByCodigo", mergeOption, codigoParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByNombreCorto(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByNombreCorto", nombreParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByNombreCorto(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByNombreCorto", mergeOption, nombreParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByRazonSocial(string razonSocial)
        {
            var razonSocialParameter = razonSocial != null ?
                new ObjectParameter("RazonSocial", razonSocial) :
                new ObjectParameter("RazonSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByRazonSocial", razonSocialParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByRazonSocial(string razonSocial, MergeOption mergeOption)
        {
            var razonSocialParameter = razonSocial != null ?
                new ObjectParameter("RazonSocial", razonSocial) :
                new ObjectParameter("RazonSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByRazonSocial", mergeOption, razonSocialParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByRUC(string rUC)
        {
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByRUC", rUCParameter);
        }
    
        public virtual ObjectResult<Empresas> SelectEmpresaByRUC(string rUC, MergeOption mergeOption)
        {
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresas>("SelectEmpresaByRUC", mergeOption, rUCParameter);
        }
    
        public virtual ObjectResult<SelectRolesPerfil_Result> SelectRolesPerfil(string idPerfilUsuario)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario != null ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectRolesPerfil_Result>("SelectRolesPerfil", idPerfilUsuarioParameter);
        }
    
        public virtual ObjectResult<PlantillaComplex> SelectPlantillaByAppRol(string idAplicacion, string idRol)
        {
            var idAplicacionParameter = idAplicacion != null ?
                new ObjectParameter("IdAplicacion", idAplicacion) :
                new ObjectParameter("IdAplicacion", typeof(string));
    
            var idRolParameter = idRol != null ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PlantillaComplex>("SelectPlantillaByAppRol", idAplicacionParameter, idRolParameter);
        }
    
        public virtual ObjectResult<OpcionUI> SelectOpcionUI(string idAplicacion)
        {
            var idAplicacionParameter = idAplicacion != null ?
                new ObjectParameter("IdAplicacion", idAplicacion) :
                new ObjectParameter("IdAplicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionUI>("SelectOpcionUI", idAplicacionParameter);
        }
    
        public virtual ObjectResult<OpcionUI> SelectOpcionUI(string idAplicacion, MergeOption mergeOption)
        {
            var idAplicacionParameter = idAplicacion != null ?
                new ObjectParameter("IdAplicacion", idAplicacion) :
                new ObjectParameter("IdAplicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionUI>("SelectOpcionUI", mergeOption, idAplicacionParameter);
        }
    
        public virtual ObjectResult<Recurso> SelectRecurso(string idRecurso)
        {
            var idRecursoParameter = idRecurso != null ?
                new ObjectParameter("IdRecurso", idRecurso) :
                new ObjectParameter("IdRecurso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecurso", idRecursoParameter);
        }
    
        public virtual ObjectResult<Recurso> SelectRecurso(string idRecurso, MergeOption mergeOption)
        {
            var idRecursoParameter = idRecurso != null ?
                new ObjectParameter("IdRecurso", idRecurso) :
                new ObjectParameter("IdRecurso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecurso", mergeOption, idRecursoParameter);
        }
    
        public virtual ObjectResult<SelectRecursoAplicacion_Result> SelectRecursoAplicacion(string idAplicacionicacion)
        {
            var idAplicacionicacionParameter = idAplicacionicacion != null ?
                new ObjectParameter("IdAplicacionicacion", idAplicacionicacion) :
                new ObjectParameter("IdAplicacionicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectRecursoAplicacion_Result>("SelectRecursoAplicacion", idAplicacionicacionParameter);
        }
    
        public virtual ObjectResult<RecursoDetalle> SelectRecursoDetalle(string idRecursoPadre)
        {
            var idRecursoPadreParameter = idRecursoPadre != null ?
                new ObjectParameter("IdRecursoPadre", idRecursoPadre) :
                new ObjectParameter("IdRecursoPadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecursoDetalle>("SelectRecursoDetalle", idRecursoPadreParameter);
        }
    
        public virtual ObjectResult<RecursoDetalle> SelectRecursoDetalle(string idRecursoPadre, MergeOption mergeOption)
        {
            var idRecursoPadreParameter = idRecursoPadre != null ?
                new ObjectParameter("IdRecursoPadre", idRecursoPadre) :
                new ObjectParameter("IdRecursoPadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecursoDetalle>("SelectRecursoDetalle", mergeOption, idRecursoPadreParameter);
        }
    
        public virtual ObjectResult<SelectRecursoPerfil_Result> SelectRecursoPerfil(string idPerfilUsuario)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario != null ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectRecursoPerfil_Result>("SelectRecursoPerfil", idPerfilUsuarioParameter);
        }
    
        public virtual ObjectResult<SelectPermiso_Result> SelectPermiso(string idRolPerfil)
        {
            var idRolPerfilParameter = idRolPerfil != null ?
                new ObjectParameter("IdRolPerfil", idRolPerfil) :
                new ObjectParameter("IdRolPerfil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPermiso_Result>("SelectPermiso", idRolPerfilParameter);
        }
    
        public virtual ObjectResult<PerfilUsuarioComplex> SelectAllPerfilUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilUsuarioComplex>("SelectAllPerfilUsuario");
        }
    
        public virtual ObjectResult<PerfilUsuarioComplex> SelectPerfilUsuarioByUser(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilUsuarioComplex>("SelectPerfilUsuarioByUser", usuarioParameter);
        }
    
        public virtual ObjectResult<PerfilUsuarioComplex> SelectPerfilUsuarioByApp(string aplicacion)
        {
            var aplicacionParameter = aplicacion != null ?
                new ObjectParameter("Aplicacion", aplicacion) :
                new ObjectParameter("Aplicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilUsuarioComplex>("SelectPerfilUsuarioByApp", aplicacionParameter);
        }
    
        public virtual ObjectResult<PerfilUsuario> SelectPerfilUsuario(string idPerfilUsuario)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario != null ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilUsuario>("SelectPerfilUsuario", idPerfilUsuarioParameter);
        }
    
        public virtual ObjectResult<PerfilUsuario> SelectPerfilUsuario(string idPerfilUsuario, MergeOption mergeOption)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario != null ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilUsuario>("SelectPerfilUsuario", mergeOption, idPerfilUsuarioParameter);
        }
    
        public virtual ObjectResult<SelectPlantilla_Result> SelectPlantilla(string idOpcionUI)
        {
            var idOpcionUIParameter = idOpcionUI != null ?
                new ObjectParameter("IdOpcionUI", idOpcionUI) :
                new ObjectParameter("IdOpcionUI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPlantilla_Result>("SelectPlantilla", idOpcionUIParameter);
        }
    
        public virtual ObjectResult<OpcionUI> SelectOpcionUIDetallado(string idOpcionPadre)
        {
            var idOpcionPadreParameter = idOpcionPadre != null ?
                new ObjectParameter("IdOpcionPadre", idOpcionPadre) :
                new ObjectParameter("IdOpcionPadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionUI>("SelectOpcionUIDetallado", idOpcionPadreParameter);
        }
    
        public virtual ObjectResult<OpcionUI> SelectOpcionUIDetallado(string idOpcionPadre, MergeOption mergeOption)
        {
            var idOpcionPadreParameter = idOpcionPadre != null ?
                new ObjectParameter("IdOpcionPadre", idOpcionPadre) :
                new ObjectParameter("IdOpcionPadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionUI>("SelectOpcionUIDetallado", mergeOption, idOpcionPadreParameter);
        }
    
        public virtual ObjectResult<OpcionUI> SelectOpcionDetalleUI(string idOpcionPadre)
        {
            var idOpcionPadreParameter = idOpcionPadre != null ?
                new ObjectParameter("IdOpcionPadre", idOpcionPadre) :
                new ObjectParameter("IdOpcionPadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionUI>("SelectOpcionDetalleUI", idOpcionPadreParameter);
        }
    
        public virtual ObjectResult<OpcionUI> SelectOpcionDetalleUI(string idOpcionPadre, MergeOption mergeOption)
        {
            var idOpcionPadreParameter = idOpcionPadre != null ?
                new ObjectParameter("IdOpcionPadre", idOpcionPadre) :
                new ObjectParameter("IdOpcionPadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionUI>("SelectOpcionDetalleUI", mergeOption, idOpcionPadreParameter);
        }
    
        public virtual ObjectResult<RecursoDetalle> SelectRecursoDetalleDetallado(string idRecursoDetallePadre)
        {
            var idRecursoDetallePadreParameter = idRecursoDetallePadre != null ?
                new ObjectParameter("IdRecursoDetallePadre", idRecursoDetallePadre) :
                new ObjectParameter("IdRecursoDetallePadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecursoDetalle>("SelectRecursoDetalleDetallado", idRecursoDetallePadreParameter);
        }
    
        public virtual ObjectResult<RecursoDetalle> SelectRecursoDetalleDetallado(string idRecursoDetallePadre, MergeOption mergeOption)
        {
            var idRecursoDetallePadreParameter = idRecursoDetallePadre != null ?
                new ObjectParameter("IdRecursoDetallePadre", idRecursoDetallePadre) :
                new ObjectParameter("IdRecursoDetallePadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecursoDetalle>("SelectRecursoDetalleDetallado", mergeOption, idRecursoDetallePadreParameter);
        }
    
        public virtual ObjectResult<Recurso> SelectRecursoDetallado(string idRecursoDetallePadre)
        {
            var idRecursoDetallePadreParameter = idRecursoDetallePadre != null ?
                new ObjectParameter("IdRecursoDetallePadre", idRecursoDetallePadre) :
                new ObjectParameter("IdRecursoDetallePadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecursoDetallado", idRecursoDetallePadreParameter);
        }
    
        public virtual ObjectResult<Recurso> SelectRecursoDetallado(string idRecursoDetallePadre, MergeOption mergeOption)
        {
            var idRecursoDetallePadreParameter = idRecursoDetallePadre != null ?
                new ObjectParameter("IdRecursoDetallePadre", idRecursoDetallePadre) :
                new ObjectParameter("IdRecursoDetallePadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecursoDetallado", mergeOption, idRecursoDetallePadreParameter);
        }
    
        public virtual ObjectResult<Recurso> SelectAllRecurso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectAllRecurso");
        }
    
        public virtual ObjectResult<Recurso> SelectAllRecurso(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectAllRecurso", mergeOption);
        }
    
        public virtual ObjectResult<Recurso> SelectRecursoByDescripcion(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecursoByDescripcion", descripcionParameter);
        }
    
        public virtual ObjectResult<Recurso> SelectRecursoByDescripcion(string descripcion, MergeOption mergeOption)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecursoByDescripcion", mergeOption, descripcionParameter);
        }
    
        public virtual ObjectResult<CargoSociedad> SelectCargoSociedad(string idCargo)
        {
            var idCargoParameter = idCargo != null ?
                new ObjectParameter("IdCargo", idCargo) :
                new ObjectParameter("IdCargo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CargoSociedad>("SelectCargoSociedad", idCargoParameter);
        }
    
        public virtual ObjectResult<CargoSociedad> SelectCargoSociedad(string idCargo, MergeOption mergeOption)
        {
            var idCargoParameter = idCargo != null ?
                new ObjectParameter("IdCargo", idCargo) :
                new ObjectParameter("IdCargo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CargoSociedad>("SelectCargoSociedad", mergeOption, idCargoParameter);
        }
    
        public virtual ObjectResult<Cargo> SelectCargo(string idCargo)
        {
            var idCargoParameter = idCargo != null ?
                new ObjectParameter("IdCargo", idCargo) :
                new ObjectParameter("IdCargo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectCargo", idCargoParameter);
        }
    
        public virtual ObjectResult<Cargo> SelectCargo(string idCargo, MergeOption mergeOption)
        {
            var idCargoParameter = idCargo != null ?
                new ObjectParameter("IdCargo", idCargo) :
                new ObjectParameter("IdCargo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectCargo", mergeOption, idCargoParameter);
        }
    
        public virtual ObjectResult<Cargo> SelectAllCargo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectAllCargo");
        }
    
        public virtual ObjectResult<Cargo> SelectAllCargo(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectAllCargo", mergeOption);
        }
    
        public virtual ObjectResult<Cargo> SelectCargoByCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectCargoByCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<Cargo> SelectCargoByCodigo(string codigo, MergeOption mergeOption)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectCargoByCodigo", mergeOption, codigoParameter);
        }
    
        public virtual ObjectResult<Cargo> SelectCargoByDescripcion(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectCargoByDescripcion", descripcionParameter);
        }
    
        public virtual ObjectResult<Cargo> SelectCargoByDescripcion(string descripcion, MergeOption mergeOption)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cargo>("SelectCargoByDescripcion", mergeOption, descripcionParameter);
        }
    
        public virtual ObjectResult<CargoSociedadComplex> SelectAllCargoSociedad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CargoSociedadComplex>("SelectAllCargoSociedad");
        }
    
        public virtual ObjectResult<SelectRecursoDetalle_Result> SelectRecursoDetalleByIdRecurso(string idRecurso)
        {
            var idRecursoParameter = idRecurso != null ?
                new ObjectParameter("IdRecurso", idRecurso) :
                new ObjectParameter("IdRecurso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectRecursoDetalle_Result>("SelectRecursoDetalleByIdRecurso", idRecursoParameter);
        }
    
        public virtual ObjectResult<Recurso> SelectRecursoForApp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecursoForApp");
        }
    
        public virtual ObjectResult<Recurso> SelectRecursoForApp(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recurso>("SelectRecursoForApp", mergeOption);
        }
    
        public virtual ObjectResult<PerfilUsuarioComplex> SelectPerfilUsuarioById(string idPerfilUsuario)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario != null ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilUsuarioComplex>("SelectPerfilUsuarioById", idPerfilUsuarioParameter);
        }
    
        public virtual ObjectResult<CargoSociedadComplex> SelectCargoSociedadBySociedad(string codSociedadPropietaria)
        {
            var codSociedadPropietariaParameter = codSociedadPropietaria != null ?
                new ObjectParameter("CodSociedadPropietaria", codSociedadPropietaria) :
                new ObjectParameter("CodSociedadPropietaria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CargoSociedadComplex>("SelectCargoSociedadBySociedad", codSociedadPropietariaParameter);
        }
    
        public virtual ObjectResult<string> GetIdPerfilUsuario(string idUsuario, string idAplicacion)
        {
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            var idAplicacionParameter = idAplicacion != null ?
                new ObjectParameter("IdAplicacion", idAplicacion) :
                new ObjectParameter("IdAplicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetIdPerfilUsuario", idUsuarioParameter, idAplicacionParameter);
        }
    
        public virtual ObjectResult<SelectPerfilUsuarioInfo_Result> SelectPerfilUsuarioInfo(string idPerfilUsuario)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario != null ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPerfilUsuarioInfo_Result>("SelectPerfilUsuarioInfo", idPerfilUsuarioParameter);
        }
    }
}
