//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gromero.Seguridad.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gromero.Seguridad.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actualizar {
            get {
                object obj = ResourceManager.GetObject("actualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Agregar {
            get {
                object obj = ResourceManager.GetObject("Agregar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Borrar {
            get {
                object obj = ResourceManager.GetObject("Borrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cambiarvista {
            get {
                object obj = ResourceManager.GetObject("cambiarvista", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clients {
            get {
                object obj = ResourceManager.GetObject("Clients", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap derecha {
            get {
                object obj = ResourceManager.GetObject("derecha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditarRol {
            get {
                object obj = ResourceManager.GetObject("EditarRol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EliminarRol {
            get {
                object obj = ResourceManager.GetObject("EliminarRol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap izquierda {
            get {
                object obj = ResourceManager.GetObject("izquierda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando se agregan Roles a la Aplicación, es posible que algunas Opciones no estén actualizadas.
        ///¿Desea continuar? Este proceso puede tardar unos minutos.
        /// </summary>
        internal static string msgActualizarOpciones {
            get {
                return ResourceManager.GetString("msgActualizarOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea actualizar todos los Perfiles de forma masiva?
        ///Este proceso podría tardar algunos minutos. ¿Desea continuar?.
        /// </summary>
        internal static string msgActualizarPerfiles {
            get {
                return ResourceManager.GetString("msgActualizarPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme.
        /// </summary>
        internal static string msgConfirme {
            get {
                return ResourceManager.GetString("msgConfirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea continuar? 
        ///Este proceso puede demorar unos minutos dependiendo de la
        ///cantidad de usuarios que ha elegido..
        /// </summary>
        internal static string msgConfirmeCreacionMasiva {
            get {
                return ResourceManager.GetString("msgConfirmeCreacionMasiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea continuar? 
        ///Se eliminarán los permisos previamente asignados a este Perfil de Usuario.
        /// </summary>
        internal static string msgEliminarPermisos {
            get {
                return ResourceManager.GetString("msgEliminarPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el lado izquierdo marque los Roles que quiera asignar a los Perfiles de Usuario.
        ///NOTA:Todos los usuarios que seleccione del lado derecho, tendrán sus respectivos perfiles en la aplicación
        ///seleccionada, tenga en cuenta que si el usuario ya tiene un Perfil creado para tal aplicación se actualizará el
        ///que ya existe y se unirán los Roles que asigne desde aquí.
        ///Presione Grabar para continuar..
        /// </summary>
        internal static string msgPerfilesMasivos {
            get {
                return ResourceManager.GetString("msgPerfilesMasivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las Opciones han sido actualizadas con éxito.
        /// </summary>
        internal static string msgSuccessActualizarOpciones {
            get {
                return ResourceManager.GetString("msgSuccessActualizarOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso de actualización de los Perfiles ha concluído de forma exitosa.
        /// </summary>
        internal static string msgSuccessActualizarPerfiles {
            get {
                return ResourceManager.GetString("msgSuccessActualizarPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuevoRol {
            get {
                object obj = ResourceManager.GetObject("nuevoRol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Preterminados {
            get {
                object obj = ResourceManager.GetObject("Preterminados", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refrescar {
            get {
                object obj = ResourceManager.GetObject("Refrescar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uncheckicon {
            get {
                object obj = ResourceManager.GetObject("uncheckicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
